// <auto-generated />
namespace My_Reading_Room.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BookView : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BookView));
        
        string IMigrationMetadata.Id
        {
            get { return "201802102056565_BookView"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
